# Generated by Django 3.2.9 on 2021-12-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename_f', models.CharField(max_length=16)),
                ('email_f', models.EmailField(max_length=254)),
                ('pass_f', models.CharField(max_length=16)),
                ('compass_f', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Post_f',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_f', models.TextField()),
                ('user_f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.user_f')),
            ],
        ),
    ]
