# Generated by Django 3.2.9 on 2021-12-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_f_user_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_f',
            name='compass_f',
        ),
    ]
